

let Humanmanage = {
  state: {
    // ULFB:{},
    // ULFE:{},
    SaveOrganization: {},
    QueryOrganization: {},
    QueryOrganizationTree: {},
    UnCancelOrganization: {},
    CancelOrganization: {},
    RemoveOrganization: {},
    QueryJobs: {},
    QueryStaff: {},
    QueryDuty: {},
    SaveJobs: {},
    SaveDutyList: {},
    CancelJobs: {},
    UnCancelJobs: {},
    RemoveJobs: {},
    RemoveDutyById: {},
    UnCancelStaff: {},
    CancelStaff: {},
    RemoveStaff: {},
    SaveStaff: {},
    QueryStaffById: {},
    QueryStaffExtend: {},
    SaveStaffExtend: {},
    SaveStaffImage: {},
    QueryStaffImage: {},
    QueryStaffMove: {},
    SaveStaffMove: {},
    QueryStaffMoveApprove: {},
    RemoveStaffImage: {},
    QueryStaffShift: {},
    QueryShift: {},
    SaveShift: {},
    UnCancelShift: {},
    CancelShift: {},
    RemoveShift: {},
    QueryHoliday: {},
    UnCancelHoliday: {},
    CancelHoliday: {},
    RemoveHoliday: {},
    SaveHoliday: {},
    QueryMakeUp: {},
    UnCancelMakeUp: {},
    CancelMakeUp: {},
    RemoveMakeUp: {},
    SaveMakeUp: {},
    QueryShiftRecord: {},
    SaveStaffShiftHand: {},
    QueryStaffTree: {},
    SaveStaffShiftP: {},
    RemoveStaffExtend: {},
    GetFrequencyPages: {},
    AddFrequency: {},
    UpdateFrequency: {},
    DeleteFrequency: {},
    GetAttendanceHolidayPages: {},
    AddAttendanceHoliday: {},
    UpdateAttendanceHoliday: {},
    DeleteAttendanceHoliday: {},
    GetAttendanceSchedulePages: {},
    DeleteAttendanceHoliday: {},
    WorkPlanTypeSave: {},
    WorkPlanTypeGetList: {},
    WorkPlanTypeDelete: {},
    InitAttendanceHolidayByApi: {},
    WorkPlanCreate: {},
    WorkPlanGetList: {},
    DeleteWorkPlanByID: {},
    WorkTaskEdit: {},
    WorkTaskGetList: {},
    WorkTaskExeGetLogList: {},
    WorkTaskSubmitExeLog: {},
    GetListWorkOrder: {},
    WorkTaskGetByID: {},
    SaveWorkOrder: {},
    GetSingleWorkOrder: {},
    // CreateBillNOByBillTypeCode:{},
    GetListWorkOrderDis: {},
    GetSingleWorkOrderDis: {},
    GetListWorkOrderLog: {},
    GetSingleWorkOrder: {},
    SaveWorkOrderLog: {},
    GetSingleWorkOrderLog: {},
    SaveWorkOrderDis: {},
    DelWorkOrder: {},
    UpdateWorkOrderConfirm: {},
    GetAttendanceSchedulePages: {},
    QueryOperationLogPages: {},
    QuerySystemErrorLogPages: {},
    AddAttendanceSchedule: {},
    LogicDeleteAttendanceSchedule: {},
    UpdateAttendanceSchedule: {},
    GetAttendanceSchedule: {},
    GetAttendanceScheduleDetail: {},
    UpdateAttendanceScheduleDetail: {},
    RemoveStaffMoveById: {}
  },
  mutations: {

  },
  actions: {

  }
}

export default Humanmanage
